spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddangbbo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wony
    password: ENC(i47xn1yWuGTFwz65qahHJydFMrc2O9ZR)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect